import { Model, DataTypes } from 'sequelize';
import db from '../Config/db_config'; // Import Sequelize instance
import { Optional } from 'sequelize';

// Define interface for Spectrogram attributes
interface SpectrogramAttributes {
  id?: number;         // Unique identifier (optional, Sequelize auto-generates for autoIncrement)
  name?: string;       // Name of the spectrogram (optional)
  data: Buffer;        // Binary data of the spectrogram
  datasetId: number;   // ID of the Dataset associated with the spectrogram
}

// Define interface for Spectrogram creation attributes
interface SpectrogramCreationAttributes extends Optional<SpectrogramAttributes, 'id' | 'name'> {}

/**
 * Spectrogram Model class
 * @class Spectrogram
 * @extends Model<SpectrogramAttributes, SpectrogramCreationAttributes>
 * @implements {SpectrogramAttributes}
 */
class Spectrogram extends Model<SpectrogramAttributes, SpectrogramCreationAttributes> implements SpectrogramAttributes {
    public id!: number;           // Unique identifier (auto-generated by Sequelize)
    public name!: string;         // Name of the spectrogram
    public data!: Buffer;         // Binary data of the spectrogram
    public datasetId!: number;    // ID of the associated Dataset

    public readonly createdAt!: Date;  // Timestamp of creation (readonly)
    public readonly updatedAt!: Date;  // Timestamp of last update (readonly)
}
  
// Initialize Spectrogram model with Sequelize
Spectrogram.init(
    {
      id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        unique: true,
        autoIncrement: true,
        allowNull: false
      },
      name: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      data: {
        type: DataTypes.BLOB,  // Binary Large Object (BLOB) for storing binary data
        allowNull: false,
      },
      datasetId: {
        type: DataTypes.INTEGER,
        allowNull: false,
      },
    },
    {
      sequelize: db,            // Sequelize instance
      modelName: 'Spectrogram', // Model name in Sequelize
      tableName: 'spectrograms', // Table name in the database
      timestamps: true,          // Enable timestamps (createdAt and updatedAt)
    }
);

// Export the Spectrogram model and its attribute interfaces
export default Spectrogram; 
export { SpectrogramAttributes, SpectrogramCreationAttributes }; 
