services:
  node_app:
    build:
      context: ./ApplicazioneNode
      dockerfile: Dockerfile
    volumes:
      - ./ApplicazioneNode:/usr/app
    depends_on:
      - flask_app
      - redis
    env_file:
      - .env  
    ports:
      - "${APP_INTERNAL_PORT}:${APP_EXTERNAL_PORT}"

  flask_app:
    build:
      context: ./DeepLearning
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${FLASK_INTERNAL_PORT}:${FLASK_EXTERNAL_PORT}"
    volumes:
      - ./DeepLearning:/usr/app

  redis:
    image: redis
    env_file:
      - .env
    ports:
      - "${REDIS_INTERNAL_PORT}:${REDIS_EXTERNAL_PORT}"
