services:
  node_app:
    build:
      context: ./ApplicazioneNode
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./ApplicazioneNode:/usr/app
    depends_on:
      - flask_app
      - redis
    env_file:
      - ./ApplicazioneNode/.env  

  flask_app:
    build:
      context: ./DeepLearning
      dockerfile: Dockerfile
    ports:
      - 8080:5000
    volumes:
      - ./DeepLearning:/usr/app

  redis:
    image: redis
    ports:
      - 6379:6379
